package com.autoheal.reporter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.concurrent.atomic.AtomicReference;

/**
 * JVM-scoped run context that resolves a single dated subfolder under the
 * configured report path for the lifetime of the JVM. All per-class reports
 * generated by the same run land inside the same folder so a cross-class
 * dashboard can aggregate them.
 */
public final class RunContext {

    private static final AtomicReference<Path> CURRENT = new AtomicReference<>();

    private RunContext() {}

    /**
     * Return the run folder, creating it on first call. Subsequent calls
     * return the same folder for the lifetime of the JVM, regardless of the
     * {@code reportRoot} passed in later calls.
     */
    public static Path getOrCreate(String reportRoot) {
        Path existing = CURRENT.get();
        if (existing != null) {
            return existing;
        }
        Path root = Paths.get(reportRoot != null ? reportRoot : ".");
        Path candidate = root.resolve(computeRunFolderName());
        if (CURRENT.compareAndSet(null, candidate)) {
            try {
                Files.createDirectories(candidate);
            } catch (IOException e) {
                System.err.println("[AutoHeal] Failed to create run folder " + candidate + ": " + e.getMessage());
            }
            return candidate;
        }
        // Lost the race; use the winning folder.
        return CURRENT.get();
    }

    /** Return the current run folder if one has been created, otherwise null. */
    public static Path current() {
        return CURRENT.get();
    }

    /** Escape hatch for daemon JVMs that want to start a fresh run. */
    public static void reset() {
        CURRENT.set(null);
    }

    private static String computeRunFolderName() {
        String override = System.getenv("AUTOHEAL_RUN_ID");
        if (override != null && !override.isEmpty()) {
            return "run_" + sanitize(override);
        }
        String ts = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss_SSS"));
        return "run_" + ts;
    }

    private static String sanitize(String value) {
        return value.replaceAll("[^A-Za-z0-9._-]", "_");
    }
}
